baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'POSTZELA'

[params]
    dateFormat = "January 2, 2006"

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "authors"
[sitemap]
    changefreq = "daily"
    priority = 0.5
    filename = "sitemap.xml"
[[params.plugins.js]]
link = "plugins/cookie.js"